### ISSUE TITLE
how it works if user refresh the page

### ISSUE THREAD

**Issue by raminahmadi1986** [havsar/node-ts-cache#2]
Hi,
consider a situation we have thousands of items to be cached , but there is an option on the page that users can go to a second page and can return to that page again , are those cached objects still available ? or if user hit refresh what would happen to the cached objects ?

**Comment by havsar** [comment]
Do you use the module in browser environment? It's not tested there yet.

**Comment by raminahmadi1986** [comment]
ok , thanks for your reply
