### ISSUE TITLE
Use real TTL with Redis

### ISSUE THREAD

**Issue by itschrono** [havsar/node-ts-cache#22]
For disk / memory usage improvement with redis I think it's better to not handle the TTL manually.
And also a TTL in milliseconds would be better imho.

**Comment by boredland** [comment]
Hi there! I implemented this on [my branch](https://github.com/boredland/node-ts-cache), when an item is neither to be cached forever nor lazy.

**Comment by havsar** [comment]
Will release v5 which will make it possible to specify the TTL in a more dynamic way. Regarding not handling the TTL manually, this is a bigger change which I will cover in a future release.
