### ISSUE TITLE
TTL is defined as seconds but used as milliseconds

### ISSUE THREAD

**Issue by hrstrand** [havsar/node-ts-cache#23]
in /packages/core/src/cache-container/cache-container.ts

the finalOptions.ttl is defined in seconds, but used in setTimeout() method, which assumes milliseconds.
If you are not using lazy cache eviction, this causes an item to be removed after 60 milliiseconds instead of 60 seconds

```ts
if (!finalOptions.isLazy) {
    setTimeout(() => {
        this.unsetKey(key)

        debug(`Expired key ${key} removed from cache`)
    }, finalOptions.ttl)
}
```

**Comment by havsar** [comment]
@hrstrand I will debug this but on the first look it seems like you are correct. Will solve this asap.

**Comment by havsar** [comment]
@hrstrand Fix will be in the next version.
