### ISSUE TITLE
How to clear cache for a single item?

### ISSUE THREAD

**Issue by MickL** [havsar/node-ts-cache#33]
I found there is a function `clear()` and expect it to clear the full cache. But how to I clear the cache only for a single value?

If this is not integrated please consider it as a feature request.

```
myCache.clearItem('key');
```

**Comment by havsar** [comment]
@MickL what about `unsetKey()`?

**Comment by MickL** [comment]
I didnt see that method as it is not documented. Anyway I cant use it because it is set to private. Also it doesnt even seem to be a method that accepts a string:

<img width="234" alt="Bildschirmfoto 2022-08-11 um 17 44 05" src="https://user-images.githubusercontent.com/5103210/184174308-0e82e161-5790-476b-87ec-28ab8745b84d.png">

**Comment by havsar** [comment]
@MickL Adding this improvement to the next minor version. Probably during next week.

**Comment by havsar** [comment]
Including this in the next release (v5).
