### ISSUE TITLE
 Property 'promisifyAll' does not exist on type 'typeof Bluebird'

### ISSUE THREAD

**Issue by AntonicaAlexandru** [havsar/node-ts-cache#8]
Hi. I've installed the module but i get this when try to instantiate the cache:

`[13:55:46] Error: TypeScript error: node_modules/node-ts-cache/src/storages/fsjsonstorage.ts(4,21): Error TS2339: Property 'promisifyAll' does not exist on type 'typeof Bluebird'.
    at formatError (C:\Users\Loki\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\format-error.js:20:10)
    at Gulp.<anonymous> (C:\Users\Loki\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\log\events.js:31:15)`

**Comment by havsar** [comment]
Hi @AntonicaAlexandru 

Can you provide more information of your environment (tsc version, node version, ...).
Do you really get the error when initializing the cache or at typescript compilation?

**Comment by angelxmoreno** [comment]
this issue is still current https://github.com/havsar/node-ts-cache/issues/14
